from app.models.domain import (
    Approval,
    ApprovalState,
    AssetType,
    Candle,
    DomainModel,
    Exchange,
    Fill,
    HealthState,
    Market,
    Order,
    OrderBook,
    OrderBookLevel,
    OrderSide,
    OrderStatus,
    OrderType,
    Position,
    PositionState,
    Quote,
    Recommendation,
    RiskState,
    Signal,
    SystemHealth,
    Trade,
    TradePlan,
)

__all__ = [
    "Approval",
    "ApprovalState",
    "AssetType",
    "Candle",
    "Exchange",
    "Fill",
    "HealthState",
    "Market",
    "Order",
    "OrderBook",
    "OrderBookLevel",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "Position",
    "PositionState",
    "Quote",
    "Recommendation",
    "RiskState",
    "Signal",
    "SystemHealth",
    "Trade",
    "TradePlan",
]

# AssetType, Exchange, and Market are enum value types (not standalone
# resources) - they appear as fields within the models below, so their
# schemas surface there rather than as top-level entries.
DOMAIN_MODELS: list[type[DomainModel]] = [
    Quote,
    Trade,
    OrderBook,
    Candle,
    Signal,
    Recommendation,
    Approval,
    TradePlan,
    Order,
    Fill,
    Position,
    RiskState,
    SystemHealth,
]
