#!/usr/bin/env python3
"""Backtest the crypto radar recommendation strategy against real Upbit
daily candles (P24).

Makes real HTTP requests to Upbit's public REST API (no API key needed -
see docs/UPBIT_NOTES.md) and replays `app/scan/crypto_backtest.py`'s
walk-forward strategy over each market's actual price history. This is the
first step of "would this strategy have made money, and should its live
recommendations be trusted enough to auto-paper-trade" - see
scripts/paper_trade_crypto.py for the second step.

Nothing here writes to the database or touches a real/paper account -
this only prints a report. `SCAN_ACCOUNT_BUYING_POWER` affects position
sizing math the same way it does in scripts/scan_crypto.py (see that
script's docstring for why it can't be fetched from Upbit itself).
"""

from __future__ import annotations

import asyncio
import os
import sys

sys.path.insert(0, ".")

import httpx

from app.core.config import get_settings
from app.integrations.upbit.rest_client import UpbitRestClient
from app.scan.crypto_backtest import BacktestResult, backtest_radar_strategy
from app.scan.crypto_scan import BENCHMARK_MARKET, LIQUIDITY_PREFILTER_SIZE

_DEFAULT_BUYING_POWER = 10_000_000.0  # KRW placeholder - see module docstring
_DEFAULT_HISTORY_DAYS = 200  # Upbit's per-request cap on any candle endpoint
_DEFAULT_MARKET_COUNT = 10  # how many of the most liquid markets to backtest


async def run() -> None:
    settings = get_settings()

    buying_power_raw = os.environ.get("SCAN_ACCOUNT_BUYING_POWER")
    account_buying_power = float(buying_power_raw) if buying_power_raw else _DEFAULT_BUYING_POWER

    market_count = int(os.environ.get("BACKTEST_MARKET_COUNT", _DEFAULT_MARKET_COUNT))
    history_days = int(os.environ.get("BACKTEST_HISTORY_DAYS", _DEFAULT_HISTORY_DAYS))

    async with httpx.AsyncClient(base_url=settings.upbit_rest_base_url) as client:
        rest = UpbitRestClient(client)

        universe = await rest.get_krw_market_universe()
        summaries = await rest.get_tickers_summary(universe)
        by_liquidity = sorted(summaries, key=lambda s: s.acc_trade_price_24h, reverse=True)
        markets = [s.market for s in by_liquidity if s.market != BENCHMARK_MARKET][
            : min(market_count, LIQUIDITY_PREFILTER_SIZE)
        ]

        benchmark_candles = await rest.get_daily_candles(BENCHMARK_MARKET, count=history_days)
        benchmark_candles.reverse()  # Upbit returns most-recent-first - see docs/UPBIT_NOTES.md

        print(f"Backtesting {len(markets)} markets over {len(benchmark_candles)} daily bars each...\n")

        results: dict[str, BacktestResult] = {}
        for market in markets:
            candles = await rest.get_daily_candles(market, count=history_days)
            candles.reverse()
            if len(candles) != len(benchmark_candles):
                print(f"{market}: skipped (only {len(candles)} bars of history, need {len(benchmark_candles)})")
                continue
            results[market] = backtest_radar_strategy(
                market, candles, benchmark_candles, account_buying_power=account_buying_power
            )

    total_trades = 0
    for market, result in sorted(results.items(), key=lambda kv: kv[1].num_trades, reverse=True):
        if result.num_trades == 0:
            print(f"{market}: no eligible breakout setups in this window")
            continue
        total_trades += result.num_trades
        print(
            f"{market}: {result.num_trades} trades, "
            f"win rate {result.win_rate * 100:.0f}%, "
            f"compounded return {result.total_return_pct * 100:+.1f}%"
        )

    if total_trades == 0:
        print("\nNo trades were generated by any market in this window - nothing to summarize.")
        return

    print(
        f"\n{total_trades} total trades across {len(results)} markets. "
        "Per-trade fees/slippage are NOT modeled here (see crypto_backtest.py's "
        "module docstring) - treat this as a signal-quality check, not a net-PnL forecast."
    )


if __name__ == "__main__":
    asyncio.run(run())
