"""add regime_relative_strength and overheat_scores tables

Revision ID: 1111690d15af
Revises: ce9c2bf2c1fa
Create Date: 2026-09-10 15:05:57.316832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1111690d15af'
down_revision: Union[str, Sequence[str], None] = 'ce9c2bf2c1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overheat_scores',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_1d_pct', sa.Float(), nullable=False),
    sa.Column('return_2d_pct', sa.Float(), nullable=False),
    sa.Column('return_5d_pct', sa.Float(), nullable=False),
    sa.Column('distance_from_signal_pct', sa.Float(), nullable=True),
    sa.Column('gap_pct', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=False),
    sa.Column('atr_extension', sa.Float(), nullable=True),
    sa.Column('heat_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'observed_at')
    )
    op.create_table('regime_relative_strength',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=False),
    sa.Column('stock_return_pct', sa.Float(), nullable=False),
    sa.Column('foreign_net_today', sa.Float(), nullable=False),
    sa.Column('institution_net_today', sa.Float(), nullable=False),
    sa.Column('market_regime', sa.String(), nullable=False),
    sa.Column('weak_market_resilience_score', sa.Float(), nullable=False),
    sa.Column('flow_resilience_score', sa.Float(), nullable=False),
    sa.Column('interaction_score', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_relative_strength_symbol'), 'regime_relative_strength', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regime_relative_strength_symbol'), table_name='regime_relative_strength')
    op.drop_table('regime_relative_strength')
    op.drop_table('overheat_scores')
    # ### end Alembic commands ###
