"""add macro_snapshots table

Revision ID: 2be085103b3e
Revises: 73383764a992
Create Date: 2026-09-10 16:26:46.016232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be085103b3e'
down_revision: Union[str, Sequence[str], None] = '73383764a992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sp500_change_pct', sa.Float(), nullable=True),
    sa.Column('sox_change_pct', sa.Float(), nullable=True),
    sa.Column('vix_level', sa.Float(), nullable=True),
    sa.Column('oil_change_pct', sa.Float(), nullable=True),
    sa.Column('usdkrw_change_pct', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_snapshots_observed_at'), 'macro_snapshots', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macro_snapshots_observed_at'), table_name='macro_snapshots')
    op.drop_table('macro_snapshots')
    # ### end Alembic commands ###
