"""add kakao_accounts table

Revision ID: 42feeed3ff50
Revises: ecebb3b3efd2
Create Date: 2026-09-06 17:31:13.929158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42feeed3ff50'
down_revision: Union[str, Sequence[str], None] = 'ecebb3b3efd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kakao_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('kakao_user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('talk_message_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kakao_accounts_kakao_user_id'), 'kakao_accounts', ['kakao_user_id'], unique=True)
    op.create_index(op.f('ix_kakao_accounts_user_id'), 'kakao_accounts', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kakao_accounts_user_id'), table_name='kakao_accounts')
    op.drop_index(op.f('ix_kakao_accounts_kakao_user_id'), table_name='kakao_accounts')
    op.drop_table('kakao_accounts')
    # ### end Alembic commands ###
