"""add approval_events table

Revision ID: 511f7209ac7b
Revises: 42feeed3ff50
Create Date: 2026-09-06 17:48:51.120428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511f7209ac7b'
down_revision: Union[str, Sequence[str], None] = '42feeed3ff50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('approval_id', sa.String(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_events_approval_id'), 'approval_events', ['approval_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_events_approval_id'), table_name='approval_events')
    op.drop_table('approval_events')
    # ### end Alembic commands ###
