"""add risk_states table

Revision ID: 5af6bb5e53bd
Revises: 511f7209ac7b
Create Date: 2026-09-07 05:58:39.749658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af6bb5e53bd'
down_revision: Union[str, Sequence[str], None] = '511f7209ac7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_loss', sa.Float(), nullable=False),
    sa.Column('daily_loss_limit', sa.Float(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=False),
    sa.Column('exposure_limit', sa.Float(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('consecutive_stops', sa.Integer(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_states_as_of'), 'risk_states', ['as_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_states_as_of'), table_name='risk_states')
    op.drop_table('risk_states')
    # ### end Alembic commands ###
