"""add stop_price and t2_price to paper_positions

Revision ID: 649cc3673d97
Revises: ddb7e52f8fec
Create Date: 2026-09-08 08:40:41.556928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649cc3673d97'
down_revision: Union[str, Sequence[str], None] = 'ddb7e52f8fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_positions', sa.Column('stop_price', sa.Float(), nullable=True))
    op.add_column('paper_positions', sa.Column('t2_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_positions', 't2_price')
    op.drop_column('paper_positions', 'stop_price')
    # ### end Alembic commands ###
