"""add P23 securities master, radar_features, radar_scores, model_weight_versions

Revision ID: 6c8f50e60bc4
Revises: 649cc3673d97
Create Date: 2026-09-08 13:03:46.175887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8f50e60bc4'
down_revision: Union[str, Sequence[str], None] = '649cc3673d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_weight_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('weights', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_weight_versions_model_name'), 'model_weight_versions', ['model_name'], unique=False)
    op.create_table('radar_features',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_return_1d', sa.Float(), nullable=True),
    sa.Column('price_return_5d', sa.Float(), nullable=True),
    sa.Column('price_return_20d', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('bollinger_width', sa.Float(), nullable=True),
    sa.Column('compression_score', sa.Float(), nullable=True),
    sa.Column('volume_ratio_5d', sa.Float(), nullable=True),
    sa.Column('value_ratio_20d', sa.Float(), nullable=True),
    sa.Column('obv_slope', sa.Float(), nullable=True),
    sa.Column('distance_20d_high', sa.Float(), nullable=True),
    sa.Column('close_location_value', sa.Float(), nullable=True),
    sa.Column('benchmark_relative_strength', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('feature_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radar_features_symbol'), 'radar_features', ['symbol'], unique=False)
    op.create_table('radar_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prebreakout_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radar_scores_scan_run_id'), 'radar_scores', ['scan_run_id'], unique=False)
    op.create_index(op.f('ix_radar_scores_symbol'), 'radar_scores', ['symbol'], unique=False)
    op.create_table('securities',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('sector_code', sa.String(), nullable=True),
    sa.Column('sector_name', sa.String(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.Column('is_etn', sa.Boolean(), nullable=False),
    sa.Column('is_spac', sa.Boolean(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('is_trading_halt', sa.Boolean(), nullable=False),
    sa.Column('is_management_issue', sa.Boolean(), nullable=False),
    sa.Column('liquidity_grade', sa.String(), nullable=True),
    sa.Column('data_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securities')
    op.drop_index(op.f('ix_radar_scores_symbol'), table_name='radar_scores')
    op.drop_index(op.f('ix_radar_scores_scan_run_id'), table_name='radar_scores')
    op.drop_table('radar_scores')
    op.drop_index(op.f('ix_radar_features_symbol'), table_name='radar_features')
    op.drop_table('radar_features')
    op.drop_index(op.f('ix_model_weight_versions_model_name'), table_name='model_weight_versions')
    op.drop_table('model_weight_versions')
    # ### end Alembic commands ###
