"""add daily_decisions table

Revision ID: 73383764a992
Revises: 1111690d15af
Create Date: 2026-09-10 15:23:59.869744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73383764a992'
down_revision: Union[str, Sequence[str], None] = '1111690d15af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_regime', sa.String(), nullable=False),
    sa.Column('minimum_score', sa.Float(), nullable=False),
    sa.Column('decision_state', sa.String(), nullable=False),
    sa.Column('top_symbol', sa.String(), nullable=True),
    sa.Column('top_symbol_name', sa.String(), nullable=True),
    sa.Column('top_normalized_score', sa.Float(), nullable=True),
    sa.Column('entry_filters_passed', sa.Integer(), nullable=True),
    sa.Column('entry_filters_total', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_decisions_observed_at'), 'daily_decisions', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_decisions_observed_at'), table_name='daily_decisions')
    op.drop_table('daily_decisions')
    # ### end Alembic commands ###
