"""add name to recommendations

Revision ID: ce9c2bf2c1fa
Revises: 6c8f50e60bc4
Create Date: 2026-09-09 12:01:13.471296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9c2bf2c1fa'
down_revision: Union[str, Sequence[str], None] = '6c8f50e60bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'name')
    # ### end Alembic commands ###
