"""initial schema

Revision ID: ecebb3b3efd2
Revises:
Create Date: 2026-09-06 04:12:56.704365

"""
import logging
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecebb3b3efd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

log = logging.getLogger("alembic.runtime.migration")

# Time-series tables meant to be TimescaleDB hypertables, per
# docs/MASTER_SPEC.md section P2, paired with their partitioning column.
HYPERTABLE_CANDIDATES = [
    ("market_ticks", "exchange_ts"),
    ("candles", "open_time"),
    ("features", "computed_at"),
    ("signals", "computed_at"),
    ("performance", "as_of"),
]


def _timescaledb_available() -> bool:
    bind = op.get_bind()
    result = bind.execute(
        sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb'")
    ).scalar()
    return result is not None


def _convert_to_hypertables() -> None:
    """Best-effort: convert time-series tables to hypertables.

    Skipped (not failed) when the `timescaledb` extension isn't installed on
    the target Postgres server - e.g. a plain `postgres` image or a local dev
    Postgres without the extension - so this migration stays portable while
    still doing the right thing against the project's real TimescaleDB
    deployment (see docker-compose.yml).
    """
    if not _timescaledb_available():
        log.warning(
            "timescaledb extension not available on this server - "
            "leaving %s as plain Postgres tables",
            ", ".join(name for name, _ in HYPERTABLE_CANDIDATES),
        )
        return

    bind = op.get_bind()
    bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS timescaledb"))
    for table_name, time_column in HYPERTABLE_CANDIDATES:
        bind.execute(
            sa.text(
                "SELECT create_hypertable(:table_name, :time_column, "
                "if_not_exists => TRUE, migrate_data => TRUE)"
            ).bindparams(table_name=table_name, time_column=time_column)
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_subject_id'), 'audit_logs', ['subject_id'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time')
    )
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'computed_at')
    )
    op.create_index(op.f('ix_features_symbol'), 'features', ['symbol'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('failure_type', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('safe_action', sa.Text(), nullable=True),
    sa.Column('recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_result', sa.String(), nullable=True),
    sa.Column('human_action_required', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_service'), 'incidents', ['service'], unique=False)
    op.create_table('market_ticks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('exchange_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'exchange_ts')
    )
    op.create_index(op.f('ix_market_ticks_symbol'), 'market_ticks', ['symbol'], unique=False)
    op.create_table('performance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'as_of')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('guardian_active', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('entry_low', sa.Float(), nullable=False),
    sa.Column('entry_high', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('t1_price', sa.Float(), nullable=False),
    sa.Column('t1_percent', sa.Float(), nullable=False),
    sa.Column('t2_price', sa.Float(), nullable=False),
    sa.Column('t2_percent', sa.Float(), nullable=False),
    sa.Column('runner_percent', sa.Float(), nullable=False),
    sa.Column('expected_max_loss', sa.Float(), nullable=False),
    sa.Column('risk_reward', sa.Float(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_symbol'), 'recommendations', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'computed_at')
    )
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_service'), 'system_health', ['service'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_approvals_recommendation_id'), 'approvals', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_approvals_user_id'), 'approvals', ['user_id'], unique=False)
    op.create_table('protective_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('trigger_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protective_orders_position_id'), 'protective_orders', ['position_id'], unique=False)
    op.create_table('trade_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('approval_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('initial_qty', sa.Float(), nullable=False),
    sa.Column('t1_percent', sa.Float(), nullable=False),
    sa.Column('t2_percent', sa.Float(), nullable=False),
    sa.Column('runner_percent', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('t1_price', sa.Float(), nullable=False),
    sa.Column('t2_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_plans_approval_id'), 'trade_plans', ['approval_id'], unique=False)
    op.create_index(op.f('ix_trade_plans_symbol'), 'trade_plans', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trade_plan_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_plan_id'], ['trade_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_trade_plan_id'), 'orders', ['trade_plan_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    # ### end Alembic commands ###

    _convert_to_hypertables()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_orders_trade_plan_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_trade_plans_symbol'), table_name='trade_plans')
    op.drop_index(op.f('ix_trade_plans_approval_id'), table_name='trade_plans')
    op.drop_table('trade_plans')
    op.drop_index(op.f('ix_protective_orders_position_id'), table_name='protective_orders')
    op.drop_table('protective_orders')
    op.drop_index(op.f('ix_approvals_user_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_recommendation_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_system_health_service'), table_name='system_health')
    op.drop_table('system_health')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_recommendations_symbol'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('performance')
    op.drop_index(op.f('ix_market_ticks_symbol'), table_name='market_ticks')
    op.drop_table('market_ticks')
    op.drop_index(op.f('ix_incidents_service'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_features_symbol'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_audit_logs_subject_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
