"""add account_balance_snapshots table

Revision ID: fd4da4748b0b
Revises: 2be085103b3e
Create Date: 2026-09-11 11:26:01.181791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4da4748b0b'
down_revision: Union[str, Sequence[str], None] = '2be085103b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_balance_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kis_total_value', sa.Float(), nullable=True),
    sa.Column('upbit_total_value', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_balance_snapshots_as_of'), 'account_balance_snapshots', ['as_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_balance_snapshots_as_of'), table_name='account_balance_snapshots')
    op.drop_table('account_balance_snapshots')
    # ### end Alembic commands ###
